name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build std
      run: cargo build -F std --verbose

    - name: Build no_std
      run: cargo build --verbose

    - name: Run tests std
      run: cargo test -F std --verbose

    - name: Run tests no_std
      run: cargo test --verbose

    - name: Run examples std
      run: cargo build -F std --example mario

    - name: Run examples no_std
      run: cargo build --example mario
